### ISSUE TITLE
Migrate benchmarks from Scala 2.12 to Scala 2.13/3.x

### ISSUE THREAD

**Issue by farquet** [renaissance-benchmarks/renaissance#324]
Opening to keep track of benchmarks still stuck on Scala 2.12.

As of Spark 3.2.0, Scala 2.13 is now supported: https://spark.apache.org/releases/spark-release-3-2-0.html

Should be eventually migrated away from 2.12 (to 2.13/3.x):

- [x] `apache-spark` benchmarks (#327)
- [ ] `reactors`
- [x] `neo4j-analytics` (#422)
- [x] `scala-stm-bench7` and `philosophers` (#445)
- [x] `finagle-http` and `finagle-chirper` (#328)

**Comment by lbulej** [comment]
Spark is basically [ready](https://github.com/renaissance-benchmarks/renaissance/tree/topic/update-spark-scala).

With `neo4j-analytics`, the problem is the **Cypher** component of Neo4j (https://github.com/neo4j/neo4j/issues/12687) that keeps it chained to Scala 2.12.

**Comment by lbulej** [comment]
With `neo4j-analytics` done (#422), we have just 3 benchmarks (in 2 modules) left.
